name: Docker Build and Push

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: axelfrache
  SERVICE_A_IMAGE: axelfrache/service-a
  SERVICE_B_IMAGE: axelfrache/service-b

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Service A
      uses: docker/build-push-action@v2
      with:
        context: ./service-a
        push: true
        tags: ${{ env.SERVICE_A_IMAGE }}:latest
        cache-from: type=registry,ref=${{ env.SERVICE_A_IMAGE }}:latest
        cache-to: type=inline
        
    - name: Build and push Service B
      uses: docker/build-push-action@v2
      with:
        context: ./service-b
        push: true
        tags: ${{ env.SERVICE_B_IMAGE }}:latest
        cache-from: type=registry,ref=${{ env.SERVICE_B_IMAGE }}:latest
        cache-to: type=inline
